<a href="https://colab.research.google.com/github/Vivekjangir90/YBI_ML_PROJECTS/blob/main/data_filling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# prompt: import pandas,numpy,matplt and seaborn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("https://github.com/Vivekjangir90/YBI_ML_PROJECTS/raw/main/train.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [21]:
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',10)

In [18]:
df.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,None,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,Mitchel,Norm,Norm,1Fam,1.5Fin,5,5,1993,1995,Gable,CompShg,VinylSd,VinylSd,None,0.0,TA,TA,Wood,Gd,TA,No,GLQ,732,Unf,0,64,796,GasA,Ex,Y,SBrkr,796,566,0,1362,1,0,1,1,1,1,TA,5,Typ,0,NaN,Attchd,1993.0,Unf,2,480,TA,TA,Y,40,30,0,320,0,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,1Story,8,5,2004,2005,Gable,CompShg,VinylSd,VinylSd,Stone,186.0,Gd,TA,PConc,Ex,TA,Av,GLQ,1369,Unf,0,317,1686,GasA,Ex,Y,SBrkr,1694,0,0,1694,1,0,2,0,3,1,Gd,7,Typ,1,Gd,Attchd,2004.0,RFn,2,636,TA,TA,Y,255,57,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,NWAmes,PosN,Norm,1Fam,2Story,7,6,1973,1973,Gable,CompShg,HdBoard,HdBoard,Stone,240.0,TA,TA,CBlock,Gd,TA,Mn,ALQ,859,BLQ,32,216,1107,GasA,Ex,Y,SBrkr,1107,983,0,2090,1,0,2,1,3,1,TA,7,Typ,2,TA,Attchd,1973.0,RFn,2,484,TA,TA,Y,235,204,228,0,0,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Artery,Norm,1Fam,1.5Fin,7,5,1931,1950,Gable,CompShg,BrkFace,Wd Shng,None,0.0,TA,TA,BrkTil,TA,TA,No,Unf,0,Unf,0,952,952,GasA,Gd,Y,FuseF,1022,752,0,1774,0,0,2,0,2,2,TA,8,Min1,2,TA,Detchd,1931.0,Unf,2,468,Fa,TA,Y,90,0,205,0,0,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,BrkSide,Artery,Artery,2fmCon,1.5Unf,5,6,1939,1950,Gable,CompShg,MetalSd,MetalSd,None,0.0,TA,TA,BrkTil,TA,TA,No,GLQ,851,Unf,0,140,991,GasA,Ex,Y,SBrkr,1077,0,0,1077,1,0,1,0,2,2,TA,5,Typ,2,TA,Attchd,1939.0,RFn,1,205,Gd,TA,Y,0,4,0,0,0,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [ ]:
null_var = df.isnull().sum()/df.shape[0]*100
null_var

In [10]:
drop_col = null_var[null_var>20].keys()
drop_col

Index(['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], dtype='object')

In [14]:
df_drop_col = df.drop(columns=drop_col)
df_drop_col.shape

(1460, 76)

In [15]:
df_num = df_drop_col.select_dtypes(include=['int64','float64'])
df_num.shape

(1460, 38)

In [22]:
a=df_num[df_num.isnull().any(axis=1)]
a

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
7,8,60,NaN,10382,7,6,1973,1973,240.0,859,32,216,1107,1107,983,0,2090,1,0,2,1,3,1,7,2,1973.0,2,484,235,204,228,0,0,0,350,11,2009,200000
12,13,20,NaN,12968,5,6,1962,1962,0.0,737,0,175,912,912,0,0,912,1,0,1,0,2,1,4,0,1962.0,1,352,140,0,0,0,176,0,0,9,2008,144000
14,15,20,NaN,10920,6,5,1960,1960,212.0,733,0,520,1253,1253,0,0,1253,1,0,1,1,2,1,5,1,1960.0,1,352,0,213,176,0,0,0,0,5,2008,157000
16,17,20,NaN,11241,6,7,1970,1970,180.0,578,0,426,1004,1004,0,0,1004,1,0,1,0,2,1,5,1,1970.0,2,480,0,0,0,0,0,0,700,3,2010,149000
24,25,20,NaN,8246,5,8,1968,2001,0.0,188,668,204,1060,1060,0,0,1060,1,0,1,0,3,1,6,1,1968.0,1,270,406,90,0,0,0,0,0,5,2010,154000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1443,1444,30,NaN,8854,6,6,1916,1950,0.0,0,0,952,952,952,0,0,952,0,0,1,0,2,1,4,1,1916.0,1,192,0,98,0,0,40,0,0,5,2009,121000
1446,1447,20,NaN,26142,5,7,1962,1962,189.0,593,0,595,1188,1188,0,0,1188,0,0,1,0,3,1,6,0,1962.0,1,312,261,39,0,0,0,0,0,4,2010,157900
1449,1450,180,21.0,1533,5,7,1970,1970,0.0,553,0,77,630,630,0,0,630,1,0,1,0,1,1,3,0,NaN,0,0,0,0,0,0,0,0,0,8,2006,92000
1450,1451,90,60.0,9000,5,5,1974,1974,0.0,0,0,896,896,896,896,0,1792,0,0,2,2,4,2,8,0,NaN,0,0,32,45,0,0,0,0,0,9,2009,136000
1453,1454,20,90.0,17217,5,5,2006,2006,0.0,0,0,1140,1140,1140,0,0,1140,0,0,1,0,3,1,6,0,NaN,0,0,36,56,0,0,0,0,0,7,2006,84500

In [24]:
df_num.isnull().sum()

Id               0
MSSubClass       0
LotFrontage    259
LotArea          0
OverallQual      0
              ...
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
SalePrice        0
Length: 38, dtype: int64

In [25]:
missing_num_var = [var for var in df_num.columns if df_num[var].isnull().sum()>0]
missing_num_var

['LotFrontage', 'MasVnrArea', 'GarageYrBlt']

In [41]:
df_num_mean = df_num.fillna(df_num.mean())
df_num_mean.isnull().sum()

Id             0
MSSubClass     0
LotFrontage    0
LotArea        0
OverallQual    0
              ..
PoolArea       0
MiscVal        0
MoSold         0
YrSold         0
SalePrice      0
Length: 38, dtype: int64

In [ ]:
sns.heatmap(df_num_mean.isnull())

In [50]:
pd.set_option('display.max_rows',100)
df_num_mean.head(100)

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,TotRmsAbvGrd,Fireplaces,GarageYrBlt,GarageCars,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.000000,8450,7,5,2003,2003,196.0,706,0,150,856,856,854,0,1710,1,0,2,1,3,1,8,0,2003.000000,2,548,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.000000,9600,6,8,1976,1976,0.0,978,0,284,1262,1262,0,0,1262,0,1,2,0,3,1,6,1,1976.000000,2,460,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.000000,11250,7,5,2001,2002,162.0,486,0,434,920,920,866,0,1786,1,0,2,1,3,1,6,1,2001.000000,2,608,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.000000,9550,7,5,1915,1970,0.0,216,0,540,756,961,756,0,1717,1,0,1,0,3,1,7,1,1998.000000,3,642,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.000000,14260,8,5,2000,2000,350.0,655,0,490,1145,1145,1053,0,2198,1,0,2,1,4,1,9,1,2000.000000,3,836,192,84,0,0,0,0,0,12,2008,250000
5,6,50,85.000000,14115,5,5,1993,1995,0.0,732,0,64,796,796,566,0,1362,1,0,1,1,1,1,5,0,1993.000000,2,480,40,30,0,320,0,0,700,10,2009,143000
6,7,20,75.000000,10084,8,5,2004,2005,186.0,1369,0,317,1686,1694,0,0,1694,1,0,2,0,3,1,7,1,2004.000000,2,636,255,57,0,0,0,0,0,8,2007,307000
7,8,60,70.049958,10382,7,6,1973,1973,240.0,859,32,216,1107,1107,983,0,2090,1,0,2,1,3,1,7,2,1973.000000,2,484,235,204,228,0,0,0,350,11,2009,200000
8,9,50,51.000000,6120,7,5,1931,1950,0.0,0,0,952,952,1022,752,0,1774,0,0,2,0,2,2,8,2,1931.000000,2,468,90,0,205,0,0,0,0,4,2008,129900
9,10,190,50.000000,7420,5,6,1939,1950,0.0,851,0,140,991,1077,0,0,1077,1,0,1,0,2,2,5,2,1939.000000,1,205,0,4,0,0,0,0,0,1,2008,118000
10,11,20,70.000000,11200,5,5,1965,1965,0.0,906,0,134,1040,1040,0,0,1040,1,0,1,0,3,1,5,0,1965.000000,1,384,0,0,0,0,0,0,0,2,2008,129500
11,12,60,85.000000,11924,9,5,2005,2006,286.0,998,0,177,1175,1182,1142,0,2324,1,0,3,0,4,1,11,2,2005.000000,3,736,147,21,0,0,0,0,0,7,2006,345000
12,13,20,70.049958,12968,5,6,1962,1962,0.0,737,0,175,912,912,0,0,912,1,0,1,0,2,1,4,0,1962.000000,1,352,140,0,0,0,176,0,0,9,2008,144000
13,14,20,91.000000,10652,7,5,2006,2007,306.0,0,0,1494,1494,1494,0,0,1494,0,0,2,0,3,1,7,1,2006.000000,3,840,160,33,0,0,0,0,0,8,2007,279500
14,15,20,70.049958,10920,6,5,1960,1960,212.0,733,0,520,1253,1253,0,0,1253,1,0,1,1,2,1,5,1,1960.000000,1,352,0,213,176,0,0,0,0,5,2008,157000
15,16,45,51.000000,6120,7,8,1929,2001,0.0,0,0,832,832,854,0,0,854,0,0,1,0,2,1,5,0,1991.000000,2,576,48,112,0,0,0,0,0,7,2007,132000
16,17,20,70.049958,11241,6,7,1970,1970,180.0,578,0,426,1004,1004,0,0,1004,1,0,1,0,2,1,5,1,1970.000000,2,480,0,0,0,0,0,0,700,3,2010,149000
17,18,90,72.000000,10791,4,5,1967,1967,0.0,0,0,0,0,1296,0,0,1296,0,0,2,0,2,2,6,0,1967.000000,2,516,0,0,0,0,0,0,500,10,2006,90000
18,19,20,66.000000,13695,5,5,2004,2004,0.0,646,0,468,1114,1114,0,0,1114,1,0,1,1,3,1,6,0,2004.000000,2,576,0,102,0,0,0,0,0,6,2008,159000
19,20,20,70.000000,7560,5,6,1958,1965,0.0,504,0,525,1029,1339,0,0,1339,0,0,1,0,3,1,6,0,1958.000000,1,294,0,0,0,0,0,0,0,5,2009,139000
20,21,60,101.000000,14215,8,5,2005,2006,380.0,0,0,1158,1158,1158,1218,0,2376,0,0,3,1,4,1,9,1,2005.000000,3,853,240,154,0,0,0,0,0,11,2006,325300
21,22,45,57.000000,7449,7,7,1930,1950,0.0,0,0,637,637,1108,0,0,1108,0,0,1,0,3,1,6,1,1930.000000,1,280,0,0,205,0,0,0,0,6,2007,139400
22,23,20,75.000000,9742,8,5,2002,2002,281.0,0,0,1777,1777,1795,0,0,1795,0,0,2,0,3,1,7,1,2002.000000,2,534,171,159,0,0,0,0,0,9,2008,230000
23,24,120,44.000000,4224,5,7,1976,1976,0.0,840,0,200,1040,1060,0,0,1060,1,0,1,0,3,1,6,1,1976.000000,2,572,100,110,0,0,0,0,0,6,2007,129900
24,25,20,70.049958,8246,5,8,1968,2001,0.0,188,668,204,1060,1060,0,0,1060,1,0,1,0,3,1,6,1,1968.000000,1,270,406,90,0,0,0,0,0,5,2010,154000
25,26,20,110.000000,14230,8,5,2007,2007,640.0,0,0,1566,1566,1600,0,0,1600,0,0,2,0,3,1,7,1,2007.000000,3,890,0,56,0,0,0,0,0,7,2009,256300
26,27,20,60.000000,7200,5,7,1951,2000,0.0,234,486,180,900,900,0,0,900,0,1,1,0,3,1,5,0,2005.000000,2,576,222,32,0,0,0,0,0,5,2010,134800
27,28,20,98.000000,11478,8,5,2007,2008,200.0,1218,0,486,1704,1704,0,0,1704,1,0,2,0,3,1,7,1,2008.000000,3,772,0,50,0,0,0,0,0,5,2010,306000
28,29,20,47.000000,16321,5,6,1957,1997,0.0,1277,0,207,1484,1600,0,0,1600,1,0,1,0,2,1,6,2,1957.000000,1,319,288,258,0,0,0,0,0,12,2006,207500
29,30,30,60.000000,6324,4,6,1927,1950,0.0,0,0,520,520,520,0,0,520,0,0,1,0,1,1,4,0,1920.000000,1,240,49,0,87,0,0,0,0,5,2008,68500
30,31,70,50.000000,8500,4,4,1920,1950,0.0,0,0,649,649,649,668,0,1317,0,0,1,0,3,1,6,0,1920.000000,1,250,0,54,172,0,0,0,0,7,2008,40000
31,32,20,70.049958,8544,5,6,1966,2006,0.0,0,0,1228,1228,1228,0,0,1228,0,0,1,1,3,1,6,0,1966.000000,1,271,0,65,0,0,0,0,0,6,2008,149350
32,33,20,85.000000,11049,8,5,2007,2007,0.0,0,0,1234,1234,1234,0,0,1234,0,0,2,0,3,1,7,0,2007.000000,2,484,0,30,0,0,0,0,0,1,2008,179900
33,34,20,70.000000,10552,5,5,1959,1959,0.0,1018,0,380,1398,1700,0,0,1700,0,1,1,1,4,1,6,1,1959.000000,2,447,0,38,0,0,0,0,0,4,2010,165500
34,35,120,60.000000,7313,9,5,2005,2005,246.0,1153,0,408,1561,1561,0,0,1561,1,0,2,0,2,1,6,1,2005.000000,2,556,203,47,0,0,0,0,0,8,2007,277500
35,36,60,108.000000,13418,8,5,2004,2005,132.0,0,0,1117,1117,1132,1320,0,2452,0,0,3,1,4,1,9,1,2004.000000,3,691,113,32,0,0,0,0,0,9,2006,309000
36,37,20,112.000000,10859,5,5,1994,1995,0.0,0,0,1097,1097,1097,0,0,1097,0,0,1,1,3,1,6,0,1995.000000,2,672,392,64,0,0,0,0,0,6,2009,145000
37,38,20,74.000000,8532,5,6,1954,1990,650.0,1213,0,84,1297,1297,0,0,1297,0,1,1,0,3,1,5,1,1954.000000,2,498,0,0,0,0,0,0,0,10,2009,153000
38,39,20,68.000000,7922,5,7,1953,2007,0.0,731,0,326,1057,1057,0,0,1057,1,0,1,0,3,1,5,0,1953.000000,1,246,0,52,0,0,0,0,0,1,2010,109000
39,40,90,65.000000,6040,4,5,1955,1955,0.0,0,0,0,0,1152,0,0,1152,0,0,2,0,2,2,6,0,1978.506164,0,0,0,0,0,0,0,0,0,6,2008,82000
40,41,20,84.000000,8658,6,5,1965,1965,101.0,643,0,445,1088,1324,0,0,1324,0,0,2,0,3,1,6,1,1965.000000,2,440,0,138,0,0,0,0,0,12,2006,160000
41,42,20,115.000000,16905,5,6,1959,1959,0.0,967,0,383,1350,1328,0,0,1328,0,1,1,1,2,1,5,2,1959.000000,1,308,0,104,0,0,0,0,0,7,2007,170000
42,43,85,70.049958,9180,5,7,1983,1983,0.0,747,93,0,840,884,0,0,884,1,0,1,0,2,1,5,0,1983.000000,2,504,240,0,0,0,0,0,0,12,2007,144000
43,44,20,70.049958,9200,5,6,1975,1980,0.0,280,491,167,938,938,0,0,938,1,0,1,0,3,1,5,0,1977.000000,1,308,145,0,0,0,0,0,0,7,2008,130250
44,45,20,70.000000,7945,5,6,1959,1959,0.0,179,506,465,1150,1150,0,0,1150,1,0,1,0,3,1,6,0,1959.000000,1,300,0,0,0,0,0,0,0,5,2006,141000
45,46,120,61.000000,7658,9,5,2005,2005,412.0,456,0,1296,1752,1752,0,0,1752,1,0,2,0,2,1,6,1,2005.000000,2,576,196,82,0,0,0,0,0,2,2010,319900
46,47,50,48.000000,12822,7,5,2003,2003,0.0,1351,0,83,1434,1518,631,0,2149,1,0,1,1,1,1,6,1,2003.000000,2,670,168,43,0,0,198,0,0,8,2009,239686
47,48,20,84.000000,11096,8,5,2006,2006,0.0,24,0,1632,1656,1656,0,0,1656,0,0,2,0,3,1,7,0,2006.000000,3,826,0,146,0,0,0,0,0,7,2007,249700
48,49,190,33.000000,4456,4,5,1920,2008,0.0,0,0,736,736,736,716,0,1452,0,0,2,0,2,3,8,0,1978.506164,0,0,0,0,102,0,0,0,0,6,2009,113000
49,50,20,66.000000,7742,5,7,1966,1966,0.0,763,0,192,955,955,0,0,955,1,0,1,0,3,1,6,0,1966.000000,1,386,0,0,0,0,0,0,0,1,2007,127000
50,51,60,70.049958,13869,6,6,1997,1997,0.0,182,0,612,794,794,676,0,1470,0,1,2,0,3,1,6,0,1997.000000,2,388,0,75,0,0,0,0,0,7,2007,177000
51,52,50,52.000000,6240,6,6,1934,1950,0.0,0,0,816,816,816,0,360,1176,0,0,1,0,3,1,6,1,1985.000000,2,528,112,0,0,0,0,0,400,9,2006,114500
52,53,90,110.000000,8472,5,5,1963,1963,0.0,104,712,0,816,816,0,0,816,1,0,1,0,2,1,5,0,1963.000000,2,516,106,0,0,0,0,0,0,5,2010,110000
53,54,20,68.000000,50271,9,5,1981,1987,0.0,1810,0,32,1842,1842,0,0,1842,2,0,0,1,0,1,5,1,1981.000000,3,894,857,72,0,0,0,0,0,11,2006,385000
54,55,80,60.000000,7134,5,5,1955,1955,0.0,384,0,0,384,1360,0,0,1360,0,0,1,0,3,1,6,1,1962.000000,2,572,0,50,0,0,0,0,0,2,2007,130000
55,56,20,100.000000,10175,6,5,1964,1964,272.0,490,0,935,1425,1425,0,0,1425,0,0,2,0,3,1,7,1,1964.000000,2,576,0,0,0,407,0,0,0,7,2008,180500
56,57,160,24.000000,2645,8,5,1999,2000,456.0,649,0,321,970,983,756,0,1739,1,0,2,1,3,1,7,0,1999.000000,2,480,115,0,0,0,0,0,0,8,2009,172500
57,58,60,89.000000,11645,7,5,2004,2004,0.0,0,0,860,860,860,860,0,1720,0,0,2,1,3,1,7,0,2004.000000,2,565,0,70,0,0,0,0,0,8,2006,196500
58,59,60,66.000000,13682,10,5,2006,2006,1031.0,0,0,1410,1410,1426,1519,0,2945,0,0,3,1,3,1,10,1,2006.000000,3,641,192,0,37,0,0,0,0,10,2006,438780
59,60,20,60.000000,7200,5,7,1972,1972,0.0,632,0,148,780,780,0,0,780,0,0,1,0,2,1,4,0,1973.000000,1,352,196,0,0,0,0,0,0,1,2008,124900
60,61,20,63.000000,13072,6,5,2004,2004,0.0,941,0,217,1158,1158,0,0,1158,1,0,1,1,3,1,5,0,2006.000000,2,576,0,50,0,0,0,0,0,5,2006,158000
61,62,75,60.000000,7200,5,7,1920,1996,0.0,0,0,530,530,581,530,0,1111,0,0,1,0,3,1,6,0,1935.000000,1,288,0,0,144,0,0,0,0,3,2007,101000
62,63,120,44.000000,6442,8,5,2006,2006,178.0,24,0,1346,1370,1370,0,0,1370,0,0,2,0,2,1,6,1,2006.000000,2,484,120,49,0,0,0,0,0,10,2007,202500
63,64,70,50.000000,10300,7,6,1921,1950,0.0,0,0,576,576,902,808,0,1710,0,0,2,0,3,1,9,0,1990.000000,2,480,12,11,64,0,0,0,0,4,2010,140000
64,65,60,70.049958,9375,7,5,1997,1998,573.0,739,0,318,1057,1057,977,0,2034,1,0,2,1,3,1,8,0,1998.000000,2,645,576,36,0,0,0,0,0,2,2009,219500
65,66,60,76.000000,9591,8,5,2004,2005,344.0,0,0,1143,1143,1143,1330,0,2473,0,0,2,1,4,1,9,1,2004.000000,3,852,192,151,0,0,0,0,0,10,2007,317000
66,67,20,70.049958,19900,7,5,1970,1989,287.0,912,0,1035,1947,2207,0,0,2207,1,0,2,0,3,1,7,1,1970.000000,2,576,301,0,0,0,0,0,0,7,2010,180000
67,68,20,72.000000,10665,7,5,2003,2003,167.0,1013,0,440,1453,1479,0,0,1479,1,0,2,0,3,1,7,0,2003.000000,2,558,144,29,0,0,0,0,0,6,2007,226000
68,69,30,47.000000,4608,4,6,1945,1950,0.0,0,0,747,747,747,0,0,747,0,0,1,0,2,1,4,0,1945.000000,1,220,0,0,0,0,0,0,0,6,2010,80000
69,70,50,81.000000,15593,7,4,1953,1953,0.0,603,0,701,1304,1304,983,0,2287,0,0,2,0,3,1,7,1,1953.000000,2,667,0,21,114,0,0,0,0,7,2006,225000
70,71,20,95.000000,13651,7,6,1973,1973,1115.0,1880,0,343,2223,2223,0,0,2223,1,0,2,0,3,1,8,2,1973.000000,2,516,300,0,0,0,0,0,0,2,2007,244000
71,72,20,69.000000,7599,4,6,1982,2006,0.0,565,0,280,845,845,0,0,845,1,0,1,0,2,1,4,0,1987.000000,2,360,0,0,0,0,0,0,0,6,2007,129500
72,73,60,74.000000,10141,7,5,1998,1998,40.0,0,0,832,832,885,833,0,1718,0,0,2,1,3,1,7,1,1998.000000,2,427,0,94,0,0,291,0,0,12,2009,185000
73,74,20,85.000000,10200,5,7,1954,2003,104.0,320,362,404,1086,1086,0,0,1086,1,0,1,0,3,1,6,0,1989.000000,2,490,0,0,0,0,0,0,0,5,2010,144900
74,75,50,60.000000,5790,3,6,1915,1950,0.0,0,0,840,840,840,765,0,1605,0,0,2,0,3,2,8,0,1915.000000,1,379,0,0,202,0,0,0,0,5,2010,107400
75,76,180,21.000000,1596,4,5,1973,1973,0.0,462,0,0,462,526,462,0,988,1,0,1,0,2,1,5,0,1973.000000,1,297,120,101,0,0,0,0,0,11,2009,91000
76,77,20,70.049958,8475,4,7,1956,1956,0.0,228,0,724,952,952,0,0,952,0,0,1,0,2,1,4,0,1956.000000,1,283,0,0,0,0,0,0,0,4,2008,135750
77,78,50,50.000000,8635,5,5,1948,2001,0.0,336,41,295,672,1072,213,0,1285,1,0,1,0,2,1,6,0,1948.000000,1,240,0,0,0,0,0,0,0,1,2008,127000
78,79,90,72.000000,10778,4,5,1968,1968,0.0,0,0,1768,1768,1768,0,0,1768,0,0,2,0,4,2,8,0,1978.506164,0,0,0,0,0,0,0,0,0,4,2010,136500
79,80,50,60.000000,10440,5,6,1910,1981,0.0,0,0,440,440,682,548,0,1230,0,0,1,1,2,1,5,0,1966.000000,2,440,74,0,128,0,0,0,0,5,2009,110000
80,81,60,100.000000,13000,6,6,1968,1968,576.0,448,0,448,896,1182,960,0,2142,0,0,2,1,4,1,8,1,1968.000000,1,509,0,72,0,0,252,0,0,6,2009,193500
81,82,120,32.000000,4500,6,5,1998,1998,443.0,1201,0,36,1237,1337,0,0,1337,1,0,2,0,2,1,5,0,1998.000000,2,405,0,199,0,0,0,0,0,3,2006,153500
82,83,20,78.000000,10206,8,5,2007,2007,468.0,33,0,1530,1563,1563,0,0,1563,0,0,2,0,3,1,6,1,2007.000000,3,758,144,99,0,0,0,0,0,10,2008,245000
83,84,20,80.000000,8892,5,5,1960,1960,66.0,0,0,1065,1065,1065,0,0,1065,0,0,1,1,3,1,6,0,1974.000000,2,461,74,0,0,0,0,0,0,7,2007,126500
84,85,80,70.049958,8530,7,5,1995,1996,22.0,0,0,384,384,804,670,0,1474,0,0,2,1,3,1,7,1,1995.000000,2,400,120,72,0,0,0,0,700,5,2009,168500
85,86,60,121.000000,16059,8,5,1991,1992,284.0,0,0,1288,1288,1301,1116,0,2417,0,0,2,1,4,1,9,1,1991.000000,2,462,127,82,0,0,0,0,0,4,2006,260000
86,87,60,122.000000,11911,6,5,2005,2005,0.0,0,0,684,684,684,876,0,1560,0,0,2,1,3,1,6,1,2005.000000,2,400,100,38,0,0,0,0,0,3,2009,174000
87,88,160,40.000000,3951,6,5,2009,2009,76.0,0,0,612,612,612,612,0,1224,0,0,2,1,2,1,4,0,2009.000000,2,528,0,234,0,0,0,0,0,6,2009,164500
88,89,50,105.000000,8470,3,2,1915,1982,0.0,0,0,1013,1013,1013,0,513,1526,0,0,1,0,2,1,6,0,1978.506164,0,0,0,0,156,0,0,0,0,10,2009,85000
89,90,20,60.000000,8070,4,5,1994,1995,0.0,588,0,402,990,990,0,0,990,1,0,1,0,3,1,5,0,1978.506164,0,0,0,0,0,0,0,0,0,8,2007,123600
90,91,20,60.000000,7200,4,5,1950,1950,0.0,0,0,0,0,1040,0,0,1040,0,0,1,0,2,1,4,0,1950.000000,2,420,0,29,0,0,0,0,0,7,2006,109900
91,92,20,85.000000,8500,5,3,1961,1961,203.0,600,0,635,1235,1235,0,0,1235,0,0,1,0,2,1,6,0,1961.000000,2,480,0,0,0,0,0,0,0,12,2006,98600
92,93,30,80.000000,13360,5,7,1921,2006,0.0,713,0,163,876,964,0,0,964,1,0,1,0,2,1,5,0,1921.000000,2,432,0,0,44,0,0,0,0,8,2009,163500
93,94,190,60.000000,7200,6,6,1910,1998,0.0,1046,0,168,1214,1260,1031,0,2291,0,1,2,0,4,2,9,1,1900.000000,2,506,0,0,0,0,99,0,0,11,2007,133900
94,95,60,69.000000,9337,6,5,1997,1997,0.0,648,0,176,824,905,881,0,1786,1,0,2,1,3,1,7,0,1997.000000,2,684,0,162,0,0,0,0,0,5,2007,204750
95,96,60,70.049958,9765,6,8,1993,1993,68.0,310,0,370,680,680,790,0,1470,0,0,2,1,3,1,6,1,1993.000000,2,420,232,63,0,0,0,0,480,4,2009,185000
96,97,20,78.000000,10264,7,5,1999,1999,183.0,1162,0,426,1588,1588,0,0,1588,0,0,2,0,3,1,6,0,1999.000000,2,472,158,29,0,0,0,0,0,8,2006,214000
97,98,20,73.000000,10921,4,5,1965,1965,48.0,520,0,440,960,960,0,0,960,1,0,1,0,3,1,6,0,1965.000000,1,432,120,0,0,0,0,0,0,5,2007,94750
98,99,30,85.000000,10625,5,5,1920,1950,0.0,108,0,350,458,835,0,0,835,0,0,1,0,2,1,5,0,1920.000000,1,366,0,0,77,0,0,0,400,5,2010,83000
99,100,20,77.000000,9320,4,5,1959,1959,0.0,569,0,381,950,1225,0,0,1225,1,0,1,1,3,1,6,0,1978.506164,0,0,352,0,0,0,0,0,400,1,2010,128950